# Generated by Django 5.1.3 on 2025-02-07 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
