# Generated by Django 5.1.3 on 2025-02-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_paymenttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('FULL_REFUND', 'Full Refund'), ('PARTIAL_REFUND', 'Partial Refund'), ('AMBIGUOUS', 'Ambiguous'), ('NOT_FOUND', 'Not Found'), ('CANCELED', 'Canceled'), ('FAILED', 'Failed')], max_length=50),
        ),
    ]
